server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springdemo?characterEncoding=UTF-8
    username: root
    password: lixf
    driver-class-name: com.mysql.jdbc.Driver

